### PR TITLE
143 add more effects in notebook

### LINKED ISSUE #143: Add more effects in notebook
https://david26694.github.io/cluster-experiments/analysis_with_different_hypothesis.html

This notebook needs more effects, otherwise this is not very representative:
imagen

### PR DESCRIPTION
**Pull request by Gabrielcidral1**
Adding more models and splitters to the hypothesis testing comparison

### CODE REVIEW

**Review by david26694 — COMMENTED** [review]
Can you add even more effects?

Something like 10 points from 0 to 0.1, I think it'll make the visualization easier to understand
imagen

**Comment by Gabrielcidral1** [comment]
I had a problem using plotnine version specified due to a conflict with numpy. I bumped plotnine locally to the latest version and it worked. Can this cause any issue here?

**Review by david26694 — CHANGES_REQUESTED** [review]
Notebook looks super good, I'd also run the missing cells or delete them. Since you changed the name of the notebook, you need to change the reference to it in mkdocs.yaml. But after that is done, lgtm

**Comment by Gabrielcidral1** [comment]
perfect, will do :)

**Comment by Gabrielcidral1** [comment]
I think it's ready to go!

**Review by david26694 — APPROVED** [review]

**Pull request merged**
